/* jshint esversion: 6 */
module.exports = {
  "resConnected": "con: connected",
  "reqAuthorize": "auth: authorize user",
  "resNoLogin": "auth: login does not exist",
  "resAuthorizeSuccess": "auth: authorized",
  "resAuthorizeFailed": "auth: incorrect password",
  "resLogoutSuccess": "",
  "reqNewuser": "newuser: create user",
  "resNewuser": "newuser: user created",
  "reqNewroom": "rooms: create new room",
  "resNewroom": "rooms: new room created",
  "reqAllRooms": "rooms: get all rooms' names",
  "resAllRooms": "rooms: all rooms' names sent",
  "resJoinCreatedRoom": "rooms: join created room",
  "reqJoinRoom": "rooms: join room",
  "resNewroomJoined": "rooms: room joined",
  "resJoinedRoomDetails": "rooms: details of joined room sent",
  "reqTakePlace": "room: take place",
  "resTakePlaceSuccess": "room: player took place",
  "reqNumberPlacesChanged": "room: number of places changed",
  "resPlacesAdded": "room: new places",
  "resPlacesRemoved": "room: places removed",
  "reqCreateScrabble": "scrabble: create",
  "resCreateScrabbleSuccess": "scrabble: created",
};
