/* jshint esversion: 6 */
module.exports = {
  "resScrabbleStateChanged": "scrabble: change the state",
  "reqScrabbleStateChangedSuccess": "scrabble: the state has been changed",
  "reqScrabbleStateChangedFailure": "scrabble: the state hasn't been changed",
  "reqCreateScrabble": "scrabble: create",
  "resCreateScrabbleSuccess": "scrabble: created",
  "resInitialTiles": "scrabble: your initial tiles",
  "reqInitialTilesSuccess": "scrabble: initial tiles received",
  "resStartRound": "scrabble: your round starts",
  "reqExchangeTiles": "scrabble: exchange tiles",
  "resExchangeTilesSuccess": "scrabble: tiles exchanged",
  "reqResign": "scrabble: I resign",
  "resResignSuccess": "scrabble: resignation accepted",
  "reqEndRound": "scrabble: end round",
  "resEndRound": "scrabble: round ended",
  "resRoundEnded": "scrabble: word accepted",
  "resWordRejected": "scrabble: word rejected",
  "resOpponentWord": "scrabble: opponent placed word",
  "reqVerifyWord": "scrabble: verify opponent's word",
  "resVerifyWordAccepted": "scrabble: opponent's word correct",
  "resVerifyWordRejected": "scrabble: opponent's word incorrect",
  "reqAcceptWord": "scrabble: I accept opponent's word",
  "resAcceptWordSuccess": "scrabble: opponent's word accepted",
  "resAcceptWordFailure": "scrabble: opponent's word rejected",
  "resOpponentExchange": "scrabble: opponent exchanged tiles",
  "resOpponentResign": "scrabble: opponent resigned"
};
