module.exports = {
  "reqTakePlace": "room: take place",
  "resTakePlaceSuccess": "room: player took place",
  "resTakePlaceFailure": "room: player failed to take place",
  "resOtherUserTookPlace": "room: other player took place",
  "reqChangeNumberPlaces": "room: change number of places",
  "resChangeNumberPlacesSuccess": "room: number of places changed",
  "resChangeNumberPlacesFailure": "room: failed to change number of places",
  "reqChangeTime": "room: change time",
  "resChangeTimeSuccess": "room: time changed",
  "resChangeTimeFailure": "room: time has not changed",
  "reqGetUp": "room: player get up",
  "resGetUpSuccess": "room: player got up",
  "resGetUpFailure": "room: player failed to get up",
  "resOtherPlayerGotUp": "room: other player got up",
  "reqLeaveRoom": "room: leave room",
  "resLeaveRoomSuccess": "room: room left",
  "resOtherUserJoinedRoom": "room: other user joined room",
  "resOtherUserLeftRoom": "room: other user left room",
  // "resAskPlayerStart": "room: ask player to start game",
  "reqStart": "room: start game",
  "resStartSuccess": "room: game started",
  "resStartFailure": "room: game not started",
  "resNotStarted": "room: game is not started",
  "resAllPlayersStarted": "room: all other players started",
  "resOwnerChanged": "room: owner changed",
  "resRoomStateChanged": "room: state changed"
};
